#!/usr/bin/env bash
# Regenerates the auto-guarded sources for the `debug-only` branch.
#
# Wraps every Swift source file in `#if DEBUG` / `#endif` so that when an app
# builds this package in its Release configuration, every target compiles to
# an EMPTY library — the linker may still receive the .o, but there is no code
# inside it. Debug builds are unaffected.
#
# Run from the repo root. Idempotent: guarded files are skipped.
set -euo pipefail
cd "$(dirname "$0")/.."

MARKER='// debug-only-branch:auto-guard (generated — do not edit this file on debug-only)'

count=0
while IFS= read -r f; do
  if head -1 "$f" | grep -q 'debug-only-branch:auto-guard'; then
    continue
  fi
  tmp="$(mktemp)"
  printf '%s\n#if DEBUG\n' "$MARKER" | cat - "$f" > "$tmp"
  printf '\n#endif\n' >> "$tmp"
  mv "$tmp" "$f"
  count=$((count + 1))
done < <(find Sources -name '*.swift' -type f | sort)

echo "guarded $count file(s)"
